name: CI/CD Pipeline for Odoo Proseit Project

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_USER: odoo
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo -d odoo"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create Dockerfile
        run: |
          cat << 'EOF' > Dockerfile
          FROM odoo:17.0
          
          USER root
          RUN apt-get update && apt-get install -y \
              python3-pip \
              build-essential \
              python3-dev \
              && rm -rf /var/lib/apt/lists/*
          
          COPY ./config/odoo.conf /etc/odoo/
          COPY ./addons /mnt/extra-addons/
          
          RUN chown -R odoo:odoo /etc/odoo/odoo.conf \
              && chown -R odoo:odoo /mnt/extra-addons
          
          USER odoo
          
          EXPOSE 8069 8071
          
          CMD ["odoo"]
          EOF

      - name: Create .env file
        run: |
          cat << EOF > .env
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          PGDATA=/var/lib/postgresql/data/pgdata
          HOST=postgres
          USER=${{ secrets.POSTGRES_USER }}
          PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOF

      - name: Create required directories and files
        run: |
          mkdir -p config addons
          echo "[options]
          addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
          admin_passwd = admin
          db_host = postgres
          db_port = 5432
          db_user = odoo
          db_password = odoo" > config/odoo.conf

      - name: Build and tag Docker Image
        run: |
          docker build -t achuka99/odoo-proseit:${{ github.sha }} \
                      -t achuka99/odoo-proseit:latest .

      - name: Start Odoo Services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for Services to be Ready
        timeout-minutes: 5
        run: |
          while ! curl -s http://127.0.0.1:8069/web/database/selector | grep -q "Databases"; do
            echo "Waiting for Odoo to be ready..."
            docker-compose logs --tail=50
            sleep 10
          done

      - name: Run Tests
        run: |
          docker-compose exec -T odoo odoo \
            --test-enable \
            --stop-after-init \
            --log-level=test \
            --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

      - name: Save Test Results
        if: always()
        run: docker-compose logs odoo > test-results.log

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.log

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            achuka99/odoo-proseit:latest
            achuka99/odoo-proseit:${{ github.sha }}
          cache-from: type=registry,ref=achuka99/odoo-proseit:latest
          cache-to: type=inline